triggers:
  cron: "@monthly"
pre_build_script:
  - apt-get -y install curl
script:
  - python3.8 -m venv venv
  - . venv/bin/activate
  - pip install --upgrade pip virtualenv
  - pip install -r test_requirements.txt
  - pip install -r scripts/requirements.txt
  - make update_package_data
  - make typecheck
  - make test
  - make build
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true
