triggers:
  cron: "@monthly"
pre_build_script:
  - apt-get -y install curl
script:
  - sed -i "s/^version = .*/version = \"$(date -u +'%Y.%-m')\"/" pyproject.toml
  - python3.10 -m venv .venv
  - . .venv/bin/activate
  - pip install --upgrade uv
  - uv pip install -e ".[dev]"
  - uv pip install -r scripts/requirements.txt
  - make update_package_data
  - make typecheck
  - make test
  - make build
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true
