# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:

  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          sudo apt install curl  # need curl to download metadata and certs for package data update

      - name: Install dependencies
        run: |
          sed -i "s/^version = .*/version = \"$(date -u +'%Y.%-m')\"/" pyproject.toml
          python -m pip install --upgrade uv
          uv venv
          uv pip install -e ".[dev]"
          uv pip install -r scripts/requirements.txt

      - name: Update package data
        run:
          make update_package_data

      - name: Test with pytest
        run: |
          make test

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sed -i "s/^version = .*/version = \"$(date -u +'%Y.%-m')\"/" pyproject.toml
          python -m pip install --upgrade uv
          uv venv
          uv pip install -e ".[dev]"

      - name: Run mypy to check types
        run: |
          uv run mypy --version
          make typecheck

